[awb]
b_gain = 1168
gb_gain = 1024
gr_gain = 1024
r_gain = 1900

[bcc]
brightness_offset = 0
contrast_gain = 256

[blc]
alpha = 0
beta = 0
bl_b = 0
bl_gb = 0
bl_gr = 0
bl_r = 0

[block_enable_status]
aaf = true
awb = true
bcc = true
blc = true
bnf = true
ccm = true
ceh = true
cfa = true
cnf = true
csc = true
dpc = true
eeh = true
fcs = true
gac = true
hsc = true
nlm = true
scl = false

[bnf]
intensity_sigma = 0.5
spatial_sigma = 0.40000000000000002
kernel_size = 5

[ccm]
matrix = [ [ 1896, -811, -62, 0 ], [ -160, 1687, -503, 0 ], [ 18, -557, 1563, 0 ] ]

[ceh]
clip_limit = 0.02
tiles = [ 4, 6 ]

[cfa]
mode = 'bilinear'

[cnf]
b_gain = 1168
diff_threshold = 0
r_gain = 2415

[dpc]
diff_threshold = 30

[eeh]
delta_threshold = 64
edge_gain = 512
edge_threshold = 4
flat_threshold = 2

[fcs]
delta_max = 16
delta_min = 4

[gac]
gain = 256
gamma = 0.41999999999999998

[hardware]
bayer_pattern = 'rggb'
raw_bit_depth = 12
raw_height = 1080
raw_width = 1920

[hsc]
hue_offset = 0
saturation_gain = 256

[nlm]
h = 4
patch_size = 5
search_window_size = 11

[scl]
height = 1024
width = 1536
